package com.jim.entity;

import java.math.BigDecimal;
import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.salt
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private Date createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	private Date updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.salt
	 * @return  the value of user.salt
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.salt
	 * @param salt  the value for user.salt
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_at
	 * @return  the value of user.create_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public Date getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_at
	 * @param createAt  the value for user.create_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_at
	 * @return  the value of user.update_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public Date getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_at
	 * @param updateAt  the value for user.update_at
	 * @mbg.generated  Thu Jul 27 02:21:50 CST 2017
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}
}